### ISSUE TITLE
Change password message

### ISSUE THREAD

**Issue by KarolinaPetrovic** [NERC-CEH/imammalia-app#10]
Please replace automated translation with the following:

Nowe hasło
To jest link jednorazowego logowania dla użytkownika kpetrovic@ibs.bialowieza.pl, który utraci ważność śr., 10/23/2019 - 12:37

Należy kliknąć Zaloguj aby zalogować się do serwisu i zmienić hasło.

Te dane logowania mogą być wykorzystane tylko jednokrotnie.

**Comment by kazlauskis** [comment]
I have now migrated this issue to another repository as this should be fixed on the website side and not the app.
