### ISSUE TITLE
Change habitat descriptions for all species

### ISSUE THREAD

**Issue by KarolinaPetrovic** [NERC-CEH/imammalia-app#17]
Jeż zachodni
Siedlisko: lasy, zarośla, łąki, pola uprawne

Królik europejski
Siedlisko: lasy, zarośla, łąki, podziemne nory

Zając szarak
Siedlisko: zarośla, łąki

Zając bielak
Siedlisko: góry, lasy, łąki

Wiewiórka pospolita
Siedlisko: lasy, zarośla, parki

Suseł perełkowany
Siedlisko: łąki, pastwiska, pola uprawne, podziemne nory

Świstak alpejski
Siedlisko: góry, łąki, podziemne nory

Bóbr europejski
Siedlisko: rzeki, cieki wodne, jeziora, bagna

Nutria amerykańska
Siedlisko: rzeki, cieki wodne, jeziora

Niedzwiedz brunatny
Siedlisko: góry, lasy, zarośla

Wilk szary
Siedlisko: góry, lasy, zarośla, łąki, pola uprawne, podziemne nory

Szakal złocisty
Siedlisko: lasy, zarośla, łąki, pola uprawne

Lis rudy
Siedlisko: lasy, zarośla, łąki, pola uprawne, podziemne nory

Jenot azjatycki
Siedlisko: lasy, zarośla, łąki, parki, podziemne nory

Szop pracz
Siedlisko: lasy, zarośla, podziemne nory

Borsuk europejski
Siedlisko: lasy, zarośla, łąki, pola uprawne, podziemne nory

Wydra europejska
Siedlisko: rzeki, cieki wodne, jeziora

Żbik europejski
Siedlisko: góry, lasy, zarośla, łąki, pola uprawne

Ryś euroazjatycki
Siedlisko: góry, lasy

Dzik euroazjatycki
Siedlisko: góry, lasy, zarośla, łąki, pola uprawne

Żubr europejski
Siedlisko: lasy, zarośla, łąki

Kozica północna
Siedlisko: góry, lasy

Jeleń szlachetny
Siedlisko: lasy, zarośla, łąki

Daniel zwyczajny
Siedlisko: lasy, zarośla

Łoś euroazjatycki
Siedlisko: rzeki, cieki wodne, bagna, lasy, łąki, pola uprawne

Sarna europejska
Siedlisko: lasy, łąki, pola uprawne

Jeleń wschodni (sika)
Siedlisko: lasy, zarośla, łąki

**Comment by kazlauskis** [comment]
If this is still relevant then please copy it to our new issue repository: https://github.com/BiologicalRecordsCentre/MammalNet-Europe/issues

I am closing this now.
