### ISSUE TITLE
Change explanation of training mode

### ISSUE THREAD

**Issue by KarolinaPetrovic** [NERC-CEH/imammalia-app#18]
Aby się dowiedzieć jak dodawać nowe obserwacje włącz "Tryb treningowy". Wszystkie obserwacje w tym trybie nie będą przesyłane dalej.

**Comment by kazlauskis** [comment]
If this is still relevant then please copy it to our new issue repository: https://github.com/BiologicalRecordsCentre/MammalNet-Europe/issues

I am closing this now.
