### ISSUE TITLE
Include occurrenceType attribute

### ISSUE THREAD

**Issue by DavidRoy** [NERC-CEH/imammalia-app#2]
New occurrence attribute required for app:

  | Occurrence type |  
-- | -- | --
  | alive | alive animals were recorded
  | dead | dead animals were recorded
  | both alive and dead | both alive and dead animals were recorded
  | indirect sign | the presence of the species was detected from indirect signs,   like tracks, excrements, vocalizations
  | other | none of the above options can apply

**Comment by kazlauskis** [comment]
After our discussion yesterday, we'll use:
* alive
* dead
* indirect (ask for more details)

**Comment by kazlauskis** [comment]
@GrahamCSmith what do you mean by 'indirect could lead to'? Is it clicking the indirect option it would expand to these 4 extra choices or is it another attribute to record altogether? or just ask for more info in the comment? thanks

**Comment by GrahamCSmith** [comment]
Yes that's right. Not sure if its easier to squeeze them all on one page or have it expanding to further choice. I'll leave that to you depending on how you think it looks.

**Comment by kazlauskis** [comment]
Yes, I like that, thanks.
