### ISSUE TITLE
iMammalia App / list of Species (Germany)

### ISSUE THREAD

**Issue by okeuling** [NERC-CEH/imammalia-app#21]
Neither the pine marten (Martes martes) nor the beech marten (Martes foinal) are included. Since, they are bigger than a mouse and quite easy to distinguish it could be useful to add them to the list in the future.[OK]  We will send a adapted list of German species

**Comment by JotablancoA** [comment]
I agree martens, mustela and Vison should be included. We have been receiving some records. A point to discuss

**Comment by kazlauskis** [comment]
If this is still relevant then please copy it to our new issue repository: https://github.com/BiologicalRecordsCentre/MammalNet-Europe/issues

I am closing this now.
