### ISSUE TITLE
List of Species in Germany

### ISSUE THREAD

**Issue by okeuling** [NERC-CEH/imammalia-app#25]
Here is the list of the recent species actually existant in Germany

•	Westigel, Braunbrustigel (Erinaceus europaeus)
•	Maulwurf (eurasischer) (Talpa europaea)

•	Waldspitzmaus (Sorex araneus)
•	Zwergspitzmaus (Sorex minutus)
•	Alpenspitzmaus (Sorex alpinus)

•	Wasserspitzmaus (Neomys fodiens)
•	Feldspitzmaus (Crocidura leucodon)
•	Sumpfspitzmaus (Neomys anomalus)
•	Gartenspitzmaus (Crocidura suaveolens)

•	Kleinhufeisennase (Rhinolophus hipposideros)
•	Großhufeisennase (Rhinolophus ferrumequinum)

•	Wasserfledermäuse (Myotis daubentoni)
•	Kleine Bartfledermaus (Myotis mystacinus)
•	Teichfledermaus (Myotis dasycneme)
•	Große Bartfledermaus (Myotis brandti)
•	Fransenfledermaus (Myotis nattereri)
•	Bechsteinfledermaus (Myotis bechsteini)
•	Mausohr, Riesenfledermaus (Myotis myotis)
•	Wimperfledermaus (Myotis emarginatus)

•	Abendsegler (Nyctalus noctula)
•	Kleinabendsegler (Nyctalus leisleri)
•	Breitflügelfledermaus (Eptesicus serotinus)
•	Nordfledermaus (Eptesicus nilssoni)
•	Zweifarbfledermaus (Vespertilio murinus)

•	Zwergfledermaus (Pipistrellus pipistrellus)
•	Rauhhautfledermaus (Pipistrellus nathusii)

•	Braunes Langohr (Plecotus auritus)
•	Graues Langohr (Plecotus austriacus)
•	Mopsfledermaus (Barbastella barbastellus)
•	Langflügelfledermaus (Miniopterus schreibersi)

•	Europäisches Wildkaninchen (Oryctolagus cuniculus)
•	Europäischer Feldhase (Lepus capensis)
•	Schneehase (Lepus timidus)

•	Eichhörnchen (Sciurus vulgaris)

•	Alpenmurmeltier (Marmota marmota)
•	Europäischer Biber (Castor fiber)
•	Nutria, Sumpfbiber (Myocastor coypus)

•	Gartenschläfer (Eliomys quercinus)
•	Siebenschläfer (Glis glis)
•	Haselmaus (Muscardinus avellanarius)

•	Hamster (Cricetus cricetus)

•	Rötelmaus, Waldwühlmaus (Clethrionomys glareolus)

•	Erdmaus (Microtus agrestis)
•	Feldmaus (Microtus arvalis)

•	Kurzohrmaus, kleinäugige Wühlmaus (Pitymys subsubterraneus)
•	Ostschermaus (Arvicola terrestris)

•	Bisamratte (Ondatra zibethicus)
•	Wanderratte (Rattus norvegicus)
•	Hausratte (Rattus rattus)

•	Waldmaus, Feld-Waldmaus (Apodemus sylvaticus)
•	Gelbhalsmaus (Apodemus flavicollis)
•	Brandmaus (Apodemus agrarius)

•	Zwergmaus (Micromys minutus)
•	Hausmaus (Mus musculus)

•	Wolf (Canis lupus)
•	Goldschakal (Canis aureus)
•	Marderhund, Enok (Nyctereutes procyonoides)
•	Rotfuchs (Vulpes vulpes)

•	Hermelin (Mustela erminea)
•	Mauswiesel (Mustela nivalis)
•	Europäischer Nerz (Mustela lutreola)
•	Amerikanischer Nerz, Mink (Mustela vison)

•	Iltis, Waldiltis (Mustela putorius)
•	Baummarder, Edelmarder (Martes martes)
•	Steinmarder (Martes foina)

•	Dachs (Meles meles)
•	Fischotter (Lutra lutra)

•	Waschbär (Procyon lotor)
•	Nordluchs (Felis lynx)
•	Wildkatze (Felis sylvestris)

•	Wildschwein (Sus scrofa)

•	Mufflon (Ovis ammon musimon)
•	Alpensteinbock (Capra ibex ibex)
•	Gemse, Gamswild (Rupicapra rupicapra)

•	Rotwild (Cervus elaphus)
•	Sikawild (Cervus nippon)
•	Damwild (Cervus dama)
•	Rehwild (Capreolus capreolus)

seldome escapes: 
Muntjak (Muntiacus reevesi)
hopefully not:
grey scirrel
burunduk

**Comment by kazlauskis** [comment]
If this is still relevant then please copy it to our new issue repository: https://github.com/BiologicalRecordsCentre/MammalNet-Europe/issues

I am closing this now.
