### ISSUE TITLE
Include RecordingMethod occurrence attribute

### ISSUE THREAD

**Issue by DavidRoy** [NERC-CEH/imammalia-app#3]
Include Recording method as occurrence attribute:

Recording method |  
-- | --
direct observation | the animals were visually detected (sighting)
camera trap | the animals were detected by a remote camera
catch | the animals were captured (and thereby detected)
road kill | the animals were found dead along a road
field carcass | the animals were found dead in their habitat
hunted | the animals were shot (and thereby detected)
telemetry | the animals were tracked by telemetry (and thereby detected)
other (specify in Notes) | none of the above options can apply

**Comment by kazlauskis** [comment]
@DavidRoy I am not sure about this one, is it just the 'hunted' that we are dropping?

**Comment by DavidRoy** [comment]
Yes, that is my understanding.  Graham can give final confirmation
