### ISSUE TITLE
Back botton on Android device and species cards

### ISSUE THREAD

**Issue by JotablancoA** [NERC-CEH/imammalia-app#6]
When you open a species card, the back button on the device closes the card. But it prevents you from opening a new card.  It gives the impression that the app is locked. However, if you go to another page and come back, you can reopen the cards.

**Comment by kazlauskis** [comment]
If this is still relevant then please copy it to our new issue repository: https://github.com/BiologicalRecordsCentre/MammalNet-Europe/issues

I am closing this now.
