### ISSUE TITLE
Change reset password email 

### ISSUE THREAD

**Issue by KarolinaPetrovic** [NERC-CEH/imammalia-app#9]
Please replace automated translation with the following:

Temat: Resetowanie hasła dla kpetrovic@ibs.bialowieza.pl na MammalNet-Europe

kpetrovic@ibs.bialowieza.pl,

W serwisie MammalNet-Europe została uruchomiona procedura resetowania Twojego hasła.

Możesz się zalogować klikając poniższy link bądź kopiując go w pole adresu przeglądarki:

https://european-mammals.brc.ac.uk/pl/user/reset/16/1571744245/bZkinoxE86XzbooR194CjREQjecZHQL0rLISdofWtAQ

Link może zostać użyty tylko raz, a jego użycie umożliwi wpisanie własnego hasła. Link straci ważność po jednym dniu.

Zespół MammalNet-Europe

**Comment by kazlauskis** [comment]
Duplicate of BiologicalRecordsCentre/MammalNet-Europe#37
